version: '3.7'

services:
  db:
    image: postgres:12.3-alpine
    ports:
     - 5432:5432
    environment:
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./boxticket_pg_data:/var/lib/postgresql/data
    networks:
      boxticket_network:
        ipv4_address: 172.18.0.6

  boxticket:
    image: boxticket:latest
    build:
      context: .
    volumes:
      - ./boxticket_static_volume:/boxticket/files/static-collected
      - ./boxticket_media_volume:/boxticket/files/media
    expose:
      - 8005
    command: >
      sh -c "python manage.py collectstatic --noinput && 
            ./wait-for-postgres.sh &&
            python manage.py makemigrations &&
            python manage.py migrate && 
            gunicorn --bind :8005 --workers 3 BoxTicket.wsgi"
    environment:
      - DEBUG=${DEBUG}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
    networks:
      boxticket_network:
        ipv4_address: 172.18.0.5
volumes:
  boxticket_pg_data:
  boxticket_static_volume:
  boxticket_media_volume:


networks:
  boxticket_network:
    ipam:
      config:
        - subnet: 172.18.0.0/16
