name: Boxticket

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          pip install -r requirements/base.txt
          pip install -r requirements/dev.txt
      - name: Run Lint
        run: flake8
      - name: Run Tests
        env:
          DB_HOST: postgres
          DB_USER: postgres
          DB_NAME: github_actions
          DB_PORT: 5432
          DB_PASSWORD: postgres
        run: pytest --cov-report term-missing --cov-config=pytest.ini --cov=./
